### PR TITLE
Fix issue where invalid content was passed to the setData method

### PR DESCRIPTION
**Pull request by kevinrademan**
Resolves https://github.com/akeneo-labs/CustomEntityBundle/issues/138

### CODE REVIEW

**Comment by jmleroux** [comment]
Thx for this PR. I'll have a look at it soon.

**Comment by kevinrademan** [comment]
Any news on this PR?

**Comment by jmleroux** [comment]
We are working on it. We are thinking about fixing it another way. Maybe in the CustomEntity normalizer.
We'll keep you asap.
Have a good one.
JM

**Comment by mmetayer** [comment]
Replaced by #146

**Pull request closed without merging**
